# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-backend-967026628831-ap-northeast-1-morrow-dev"
    encrypt = true
    key     = "envs/dev/ap-northeast-1/tf.tfstate"
    region  = "ap-northeast-1"
  }
}
