# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ap-northeast-1"

  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["967026628831"]
}
