services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ..:/workspace/morrow
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
  postgres:
    image: postgres:16
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      timeout: 30s
      retries: 3
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      postgres:
        condition: service_healthy
    # restart: always
    ports:
      - 8080:8080

  # schemaspy:
  #   image: schemaspy/schemaspy
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./schemaspy/schemaspy.properties:/schemaspy.properties
  #     - ./schemaspy/output:/output
  # schemaspy_web:
  #   image: nginx
  #   depends_on:
  #     - schemaspy
  #   ports:
  #     - 1432:80
  #   volumes:
  #     - ./schemaspy/output:/usr/share/nginx/html

volumes:
  postgres-data:
