services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ..:/workspace/morrow
    depends_on:
      - mysql
    ports:
      - 3000:3000
  mysql:
    image: mysql:lts
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 3
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  schemaspy:
    image: schemaspy/schemaspy
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./schemaspy/schemaspy.properties:/schemaspy.properties
      - ./schemaspy/output:/output
  schemaspy_web:
    image: nginx
    depends_on:
      - schemaspy
    ports:
      - 8080:80
    volumes:
      - ./schemaspy/output:/usr/share/nginx/html

volumes:
  mysql-data:
